export const SET_AUTH_CHECKED: "SET_AUTH_CHECKED" = "SET_AUTH_CHECKED";
export const SET_USER: "SET_USER" = "SET_USER";

export const REGISTER_REQUEST: "REGISTER_REQUEST" = "REGISTER_REQUEST";
export const REGISTER_ERROR: "REGISTER_ERROR" = "REGISTER_ERROR";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";

export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_ERROR: "GET_USER_ERROR" = "GET_USER_ERROR";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";

export const UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST" = "UPDATE_USER_REQUEST";
export const UPDATE_USER_ERROR: "UPDATE_USER_ERROR" = "UPDATE_USER_ERROR";
export const UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS" = "UPDATE_USER_SUCCESS";

export const SIGN_IN_REQUEST: "SIGN_IN_REQUEST" = "SIGN_IN_REQUEST";
export const SIGN_IN_ERROR: "SIGN_IN_ERROR" = "SIGN_IN_ERROR";
export const SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS" = "SIGN_IN_SUCCESS";

export const SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST" = "SIGN_OUT_REQUEST";
export const SIGN_OUT_ERROR: "SIGN_OUT_ERROR" = "SIGN_OUT_ERROR";
export const SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS" = "SIGN_OUT_SUCCESS";
