export const CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST" =
  "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_ERROR: "CREATE_ORDER_ERROR" = "CREATE_ORDER_ERROR";
export const CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS" =
  "CREATE_ORDER_SUCCESS";

export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_ERROR: "GET_ORDER_ERROR" = "GET_ORDER_ERROR";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
