export const PROFILE_ORDERS_CONNECT: "PROFILE_ORDERS_CONNECT" = "PROFILE_ORDERS_CONNECT";
export const PROFILE_ORDERS_DISCONNECT: "PROFILE_ORDERS_DISCONNECT" = "PROFILE_ORDERS_DISCONNECT";
export const PROFILE_ORDERS_WS_CONNECTING: "PROFILE_ORDERS_WS_CONNECTING" = "PROFILE_ORDERS_WS_CONNECTING";
export const PROFILE_ORDERS_WS_OPEN: "PROFILE_ORDERS_WS_OPEN" = "PROFILE_ORDERS_WS_OPEN";
export const PROFILE_ORDERS_WS_CLOSE: "PROFILE_ORDERS_WS_CLOSE" = "PROFILE_ORDERS_WS_CLOSE";
export const PROFILE_ORDERS_WS_MESSAGE: "PROFILE_ORDERS_WS_MESSAGE" = "PROFILE_ORDERS_WS_MESSAGE";
export const PROFILE_ORDERS_WS_ERROR: "PROFILE_ORDERS_WS_ERROR" = "PROFILE_ORDERS_WS_ERROR";